/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ndk_demo_com_bsdiff_server_Bsdiff */

#ifndef _Included_ndk_demo_com_bsdiff_server_Bsdiff
#define _Included_ndk_demo_com_bsdiff_server_Bsdiff
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ndk_demo_com_bsdiff_server_Bsdiff
 * Method:    diff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ndk_demo_com_bsdiff_1server_Bsdiff_diff
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
